services:
  postgres:
    image: postgres:16
    container_name: bigdata_snowflake_pg
    environment:
      POSTGRES_DB: bigdata
      POSTGRES_USER: bigdata
      POSTGRES_PASSWORD: bigdata
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/data:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bigdata -d bigdata"]
      interval: 5s
      timeout: 3s
      retries: 20
